include $(CLEAR_VARS)
LOCAL_MODULE := Bromite
LOCAL_SRC_FILES := arm64_ChromePublic.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_SUFFIX := .apk

LOCAL_REQUIRED_MODULES := bromite_repos.xml
include $(BUILD_PREBUILT)
