# override lineageOSnoLOSEmail
include $(CLEAR_VARS)
LOCAL_MODULE := noLOSEmail
LOCAL_SRC_FILES := empty.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_SUFFIX := .apk
LOCAL_OVERRIDES_PACKAGES := Email
include $(BUILD_PREBUILT)

# override lineageOS Messaging
include $(CLEAR_VARS)
LOCAL_MODULE := noLOSMessaging
LOCAL_SRC_FILES := empty.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_SUFFIX := .apk
LOCAL_OVERRIDES_PACKAGES := messaging
include $(BUILD_PREBUILT)

# override lineageOS Snap
include $(CLEAR_VARS)
LOCAL_MODULE := noLOSSnap
LOCAL_SRC_FILES := empty.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_SUFFIX := .apk
LOCAL_OVERRIDES_PACKAGES := Snap
include $(BUILD_PREBUILT)

# override lineageOS Jelly
include $(CLEAR_VARS)
LOCAL_MODULE := noLOSJelly
LOCAL_SRC_FILES := empty.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_SUFFIX := .apk
LOCAL_OVERRIDES_PACKAGES := Jelly
include $(BUILD_PREBUILT)
