include $(CLEAR_VARS)
LOCAL_MODULE := DAVx5
LOCAL_SRC_FILES := prebuilt/at.bitfire.davdroid_LATEST.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_SUFFIX := .apk

include $(BUILD_PREBUILT)
