include $(CLEAR_VARS)
LOCAL_MODULE := UpstreamEtar
LOCAL_SRC_FILES := ws.xsoh.etar_32.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_SUFFIX := .apk
LOCAL_OVERRIDES_PACKAGES := Etar
include $(BUILD_PREBUILT)
